import {ads} from './ads.js?v=mp4-5';
import {safeDestination} from './url.js';
const $=s=>document.querySelector(s),dialog=$('#delivery'),motion=matchMedia('(prefers-reduced-motion: reduce)');
let paused=motion.matches,selected=null,mode='iframe';
const media=(id,poster=false)=>new URL(`../assets/${id}${poster?'-poster':''}.webp?v=${ads.find(ad=>ad.id===id)?.bytes}`,import.meta.url).href;
const videoMedia=id=>new URL(`../assets/${id}.mp4?v=${ads.find(ad=>ad.id===id)?.mp4Bytes}`,import.meta.url).href;
const size=n=>n<1e6?`${Math.round(n/1000)} KB`:`${(n/1e6).toFixed(2)} MB`;
$('#count').textContent=`${ads.length} 款`;
for(const ad of ads){const card=document.createElement('article');card.className='card';card.innerHTML='<div class="art"><video width="600" height="400" muted loop playsinline preload="none"></video></div><div class="info"><div class="title-row"><h3></h3><span class="badge">双模式</span></div><p class="facts"></p><div class="card-actions"><button class="primary" type="button">iframe 嵌入</button><button class="secondary mp4" type="button">MP4 影片</button><button class="secondary webp" type="button">動畫 WebP</button></div></div>';card.querySelector('h3').textContent=ad.name;card.querySelector('.badge').textContent='三種用法';card.querySelector('.facts').textContent=`600 × 400 · MP4 ${size(ad.mp4Bytes)} · WebP ${size(ad.bytes)} · ${ad.seconds} 秒循環`;const img=card.querySelector('video');img.setAttribute('aria-label',ad.name+'廣告動畫');img.muted=true;img.poster=media(ad.id,true);img.dataset.id=ad.id;card.querySelector('.primary').onclick=()=>openAd(ad,'iframe');card.querySelector('.mp4').onclick=()=>openAd(ad,'mp4');card.querySelector('.webp').onclick=()=>openAd(ad,'webp');$('#gallery').append(card);}
const observer=new IntersectionObserver(entries=>{for(const e of entries){e.target.dataset.visible=String(e.isIntersecting);syncVideo(e.target);}},{rootMargin:'100px'});
function syncVideo(video){if(paused||video.dataset.visible!=='true'){video.pause();return;}if(!video.src)video.src=videoMedia(video.dataset.id);video.play().catch(()=>{});}
for(const video of $('#gallery').querySelectorAll('video'))observer.observe(video);
function renderMotion(){for(const video of $('#gallery').querySelectorAll('video'))syncVideo(video);$('#motion').textContent=paused?'播放預覽':'暫停預覽';$('#motion').setAttribute('aria-pressed',String(paused));}
$('#motion').onclick=()=>{paused=!paused;renderMotion();};motion.addEventListener('change',()=>{paused=motion.matches;renderMotion();});renderMotion();
function saved(id){try{return localStorage.getItem('banner-destination:'+id)||'';}catch{return '';}}
function remember(id,value){try{localStorage.setItem('banner-destination:'+id,value);}catch{}}
function setMode(next){mode=next;$('#iframe-panel').hidden=mode!=='iframe';$('#webp-panel').hidden=mode!=='webp';$('#mp4-panel').hidden=mode!=='mp4';for(const button of document.querySelectorAll('[data-mode]'))button.setAttribute('aria-pressed',String(button.dataset.mode===mode));$('#status').textContent='';}
function makeURL(){const url=new URL('../embed.html',import.meta.url);url.searchParams.set('id',selected.id);const destination=safeDestination($('#destination').value);if(destination)url.searchParams.set('url',destination);return url;}
function refresh(){const value=$('#destination').value.trim(),destination=safeDestination(value);$('#url-error').hidden=!value||Boolean(destination);$('#url-error').textContent='請填寫完整的 https:// 或 http:// 活動網址。';const url=makeURL();$('#preview').src=url.href;const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');$('#code').value=`<iframe src="${escape(url.href)}" title="${selected.name}廣告" width="600" height="400" style="display:block;width:100%;max-width:600px;height:auto;aspect-ratio:3/2;border:0" loading="lazy"></iframe>`;if(destination||!value)remember(selected.id,destination||'');$('#status').textContent='';}
function openAd(ad,next){selected=ad;$('#dialog-title').textContent=ad.name;$('#facts').textContent=`600 × 400 · MP4 ${size(ad.mp4Bytes)} · WebP ${size(ad.bytes)} · ${ad.seconds} 秒循環 · iframe 播放 MP4，另提供 WebP 下載`;$('#destination').value=saved(ad.id);$('#download-mp4').href=videoMedia(ad.id);$('#download-mp4').download=`${ad.id}-600x400.mp4`;$('#download-mp4').textContent=`↓ 下載 MP4（${size(ad.mp4Bytes)}）`;$('#download').href=media(ad.id);$('#download').download=`${ad.id}-600x400.webp`;$('#download').textContent=`↓ 下載動畫 WebP（${size(ad.bytes)}）`;const local=['127.0.0.1','localhost','[::1]'].includes(location.hostname);$('#hosting').textContent=local?'目前為本機測試。正式投放前，請將此系統上傳到公開 HTTPS 網址，再從該網址複製嵌入碼。':'嵌入碼會從本站載入動畫；廣告點擊後另開活動頁。';setMode(next);refresh();dialog.showModal();}
$('#destination').addEventListener('change',refresh);
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
$('#close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{const value=$('#destination').value.trim(),destination=safeDestination(value);if(selected&&(destination||!value))remember(selected.id,destination||'');$('#preview').src='about:blank';});
$('#copy').onclick=async()=>{const destination=safeDestination($('#destination').value);if(!destination){$('#url-error').hidden=false;$('#url-error').textContent='先填入活動網址，客戶點廣告才有地方可以前往。';$('#destination').focus();return;}refresh();try{await navigator.clipboard.writeText($('#code').value);$('#status').textContent='已複製！貼到網站的 HTML 區塊即可。';}catch{$('#code').focus();$('#code').select();$('#status').textContent='已選取嵌入碼，請按 Command+C 或 Ctrl+C 複製。';}};
